[package]
name = "rust-tx"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
itertools = "0.10.5"
iterx = "0.0.10"
# iterx = { path = "../rust-iterx" }
